version: "3"

services:
    sut:
        build:
            context: ../../.
            dockerfile: docker/images/Dockerfile.test
        command: /opt/tests/run_test.sh
        depends_on:
            - explorer

    explorer:
        build:
            context: ../../.
            dockerfile: docker/images/Dockerfile
